// LocalizationStore.swift
// Selector de idioma en tiempo de ejecucion: 11 idiomas.

import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case es = "es"
    case en = "en"
    case fr = "fr"
    case it = "it"
    case de = "de"
    case zh = "zh"
    case ja = "ja"
    case th = "th"
    case ca = "ca"
    case gl = "gl"
    case eu = "eu"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .es: return "Español"
        case .en: return "English"
        case .fr: return "Français"
        case .it: return "Italiano"
        case .de: return "Deutsch"
        case .zh: return "中文"
        case .ja: return "日本語"
        case .th: return "ภาษาไทย"
        case .ca: return "Català"
        case .gl: return "Galego"
        case .eu: return "Euskera"
        }
    }

    var flag: String {
        switch self {
        case .es: return "ES"
        case .en: return "EN"
        case .fr: return "FR"
        case .it: return "IT"
        case .de: return "DE"
        case .zh: return "ZH"
        case .ja: return "JA"
        case .th: return "TH"
        case .ca: return "CA"
        case .gl: return "GL"
        case .eu: return "EU"
        }
    }
}

final class LocalizationStore: ObservableObject {
    @Published var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: "sc.language") }
    }

    init() {
        let saved = UserDefaults.standard.string(forKey: "sc.language") ?? "es"
        self.language = AppLanguage(rawValue: saved) ?? .es
    }

    func t(_ key: String) -> String {
        strings[language]?[key] ?? strings[.es]?[key] ?? key
    }

    // MARK: - Diccionario de cadenas

    private let strings: [AppLanguage: [String: String]] = [

        .es: [
            // Header
            "header.master": "MASTER",
            "header.key": "TECLADO",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "ANCLADO",
            // Deck
            "deck.notLoaded": "SIN PISTA",
            "deck.noTitle": "SIN TITULO",
            "deck.play": "PLAY",
            "deck.pause": "PAUSA",
            "deck.stop": "STOP",
            "deck.lock": "LOCK",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            // Settings sections
            "settings.title": "CONFIG",
            "settings.subtitle": "AJUSTES",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historial",
            "settings.labels": "Etiquetas",
            "settings.mapping": "Mapeo",
            "settings.license": "Licencia",
            "settings.language": "Idioma",
            "settings.appearance": "Apariencia",
            "settings.sources": "FUENTES",
            "settings.sources.subtitle": "Activa o desactiva cada protocolo. Auto y Todos respetan estos ticks.",
            "settings.sources.all": "Todos",
            "settings.sources.hint": "En cabecera, Auto usa estos ticks. Denon/Pioneer/… exclusivos ignoran el resto. Dual se unificó en Auto.",
            "settings.updates": "Actualizaciones",
            // Appearance
            "appearance.title": "APARIENCIA",
            "appearance.dark": "Modo oscuro",
            "appearance.light": "Modo claro",
            "appearance.toggle": "Cambiar modo",
            // Language
            "language.title": "IDIOMA",
            "language.select": "Seleccionar idioma",
            // License
            "license.activate": "Activar",
            "license.deactivate": "Desactivar",
            "license.active": "Licencia activa",
            "license.inactive": "Sin licencia",
            "license.monthly": "Mensual",
            "license.lifetime": "Vitalicio",
            "license.code": "Codigo de activacion",
            "license.enter": "Introduce el codigo...",
            // Common
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Guardar",
            "common.cancel": "Cancelar",
            "common.close": "Cerrar",
            "common.noSignal": "sin señal",
            "common.clock": "RELOJ",
            "empty.searching": "Buscando reproductores en la red…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "Contenido",
            "obs.tc": "Timecode (TC)",
            "obs.title": "Título",
            "obs.artwork": "Portada",
            "obs.meta": "Metadatos (BPM, key, artista)",
            "obs.decks": "Decks",
            "appearance.dark.short": "Oscuro",
            "appearance.light.short": "Claro",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER es el LTC de casa: un playhead, N salidas. Sigue al deck master / On Air / el que suena.",
            "ltc.master.home": "MASTER DE CASA",
            "ltc.network.emergency": "Emergencia de red",
            "ltc.outputs.master": "Salidas Master",
            "ltc.outputs.hint": "Elige una o varias. El mismo TC se duplica en cada device.",
            "ltc.per.player": "POR REPRODUCTOR",
            "ltc.no.players": "No hay reproductores visibles. Carga una pista para asignar salidas.",
            "ltc.outputs": "Salidas",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "Timecode MIDI para DAW y luces.",
            "mtc.port.hint": "El puerto aparece en Audio MIDI Setup → Studio MIDI → STAGE CONNECT MTC.",
            "osc.title": "OSC a Resolume",
            "osc.subtitle": "Tempo y playhead hacia Resolume Arena / Avenue.",
            "web.title": "Servidor web",
            "web.subtitle": "Monitor en el navegador, JSON y WebSocket para overlay (Resolume, OBS).",
            "web.on.this.mac": "En este Mac",
            "web.on.lan": "En la red (otro equipo)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "Añade un Browser Source 1920×1080. Elige qué se muestra.",
            "obs.enable.web": "Activa el servidor web para obtener la URL. OBS: Browser Source, 1920×1080, FPS 30.",
            "history.title": "Historial de reproducción",
            "history.subtitle": "Lista de pistas que han sonado en esta sesión.",
            "history.empty": "El historial se llena automáticamente cuando suenan pistas.",
            "labels.title": "Etiquetas de decks",
            "labels.subtitle": "Nombres cortos personalizados para cada reproductor.",
            "labels.open.monitor": "Abrir MONITOR",
            "labels.open.setlist": "Abrir SETLIST",
            "labels.empty": "Ninguna etiqueta personalizada. Clic en A/1 de una fila para cambiarla.",
            "mapping.title": "Mapeo",
            "mapping.subtitle": "Atajos de teclado y MIDI learn para cabecera y SMPTE.",
            "mapping.first.device": "Primer dispositivo",
            "mapping.hint.dual": "F1–F4 son las primeras 4 filas visibles (SMPTE). Auto admite CDJ + capas Denon.",
            "appearance.subtitle": "Modo oscuro o claro de la interfaz.",
            "appearance.hint": "El modo claro adapta el fondo y el texto. Los colores de acento, LED y waveform no cambian.",
            "updates.title": "Actualizaciones",
            "updates.subtitle": "Comprueba y descarga la última versión de STAGE CONNECT.",
            "updates.notes": "Notas",
            "updates.action": "ACTUALIZAR",
            "license.title": "Licencia",
            "license.subtitle": "Estado de activación de STAGE CONNECT.",
            "license.remove": "QUITAR LICENCIA",

            "monitor.title": "MONITOR",
            "monitor.options": "OPCIONES",
            "monitor.day": "DÍA",
            "monitor.night": "NOCHE",
            "monitor.on.top": "ENCIMA",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "OPACIDAD",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "ONDA",
            "monitor.opt.art": "PORTADA",
            "monitor.opt.artist": "ARTISTA",
            "monitor.noMaster": "SIN MASTER",
            "monitor.mode.window": "VENTANA",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "Solo TC",
            "monitor.layout.data": "Solo datos",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "Cabina",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "Transparente",

        ],

        .en: [
            "header.master": "MASTER",
            "header.key": "KEYBOARD",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "PINNED",
            "deck.notLoaded": "NO TRACK",
            "deck.noTitle": "NO TITLE",
            "deck.play": "PLAY",
            "deck.pause": "PAUSE",
            "deck.stop": "STOP",
            "deck.lock": "LOCK",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "SETTINGS",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "History",
            "settings.labels": "Labels",
            "settings.mapping": "Mapping",
            "settings.license": "License",
            "settings.language": "Language",
            "settings.appearance": "Appearance",
            "settings.sources": "SOURCES",
            "settings.sources.subtitle": "Enable or disable each protocol. Auto and All respect these ticks.",
            "settings.sources.all": "All",
            "settings.sources.hint": "In the header, Auto uses these ticks. Exclusive Denon/Pioneer/… ignore the rest. Dual merged into Auto.",
            "settings.updates": "Updates",
            "appearance.title": "APPEARANCE",
            "appearance.dark": "Dark mode",
            "appearance.light": "Light mode",
            "appearance.toggle": "Toggle mode",
            "language.title": "LANGUAGE",
            "language.select": "Select language",
            "license.activate": "Activate",
            "license.deactivate": "Deactivate",
            "license.active": "License active",
            "license.inactive": "No license",
            "license.monthly": "Monthly",
            "license.lifetime": "Lifetime",
            "license.code": "Activation code",
            "license.enter": "Enter code...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Save",
            "common.cancel": "Cancel",
            "common.close": "Close",
            "common.noSignal": "no signal",
            "common.clock": "CLOCK",
            "empty.searching": "Searching for players on the network…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "Content",
            "obs.tc": "Timecode (TC)",
            "obs.title": "Title",
            "obs.artwork": "Artwork",
            "obs.meta": "Metadata (BPM, key, artist)",
            "obs.decks": "Decks",
            "appearance.dark.short": "Dark",
            "appearance.light.short": "Light",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER is house LTC: one playhead, N outputs. Follows master / On Air / playing deck.",
            "ltc.master.home": "HOUSE MASTER",
            "ltc.network.emergency": "Network emergency",
            "ltc.outputs.master": "Master outputs",
            "ltc.outputs.hint": "Pick one or more. The same TC is duplicated on each device.",
            "ltc.per.player": "PER PLAYER",
            "ltc.no.players": "No visible players. Load a track to assign outputs.",
            "ltc.outputs": "Outputs",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "MIDI timecode for DAW and lights.",
            "mtc.port.hint": "The port appears in Audio MIDI Setup → MIDI Studio → STAGE CONNECT MTC.",
            "osc.title": "OSC to Resolume",
            "osc.subtitle": "Tempo and playhead to Resolume Arena / Avenue.",
            "web.title": "Web server",
            "web.subtitle": "Browser monitor, JSON and WebSocket for overlays (Resolume, OBS).",
            "web.on.this.mac": "On this Mac",
            "web.on.lan": "On the network (another machine)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "Add a 1920×1080 Browser Source. Choose what is shown.",
            "obs.enable.web": "Enable the web server to get the URL. OBS: Browser Source, 1920×1080, 30 FPS.",
            "history.title": "Playback history",
            "history.subtitle": "Tracks that played in this session.",
            "history.empty": "History fills automatically when tracks play.",
            "labels.title": "Deck labels",
            "labels.subtitle": "Custom short names for each player.",
            "labels.open.monitor": "Open MONITOR",
            "labels.open.setlist": "Open SETLIST",
            "labels.empty": "No custom labels. Click A/1 on a row to rename.",
            "mapping.title": "Mapping",
            "mapping.subtitle": "Keyboard shortcuts and MIDI learn for header and SMPTE.",
            "mapping.first.device": "First device",
            "mapping.hint.dual": "F1–F4 are the first 4 visible rows (SMPTE). Auto supports CDJ + Denon layers.",
            "appearance.subtitle": "Dark or light UI mode.",
            "appearance.hint": "Light mode adapts background and text. Accent, LED and waveform colors stay the same.",
            "updates.title": "Updates",
            "updates.subtitle": "Check and download the latest STAGE CONNECT.",
            "updates.notes": "Notes",
            "updates.action": "UPDATE",
            "license.title": "License",
            "license.subtitle": "STAGE CONNECT activation status.",
            "license.remove": "REMOVE LICENSE",

            "monitor.title": "MONITOR",
            "monitor.options": "OPTIONS",
            "monitor.day": "DAY",
            "monitor.night": "NIGHT",
            "monitor.on.top": "ON TOP",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "OPACITY",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "WAVE",
            "monitor.opt.art": "COVER",
            "monitor.opt.artist": "ARTIST",
            "monitor.noMaster": "NO MASTER",
            "monitor.mode.window": "WINDOW",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "TC only",
            "monitor.layout.data": "Data only",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "Booth",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "Transparent",

        ],

        .fr: [
            "header.master": "MASTER",
            "header.key": "CLAVIER",
            "header.midi": "MIDI",
            "header.monitor": "MONITEUR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "FIXE",
            "deck.notLoaded": "SANS PISTE",
            "deck.noTitle": "SANS TITRE",
            "deck.play": "PLAY",
            "deck.pause": "PAUSE",
            "deck.stop": "STOP",
            "deck.lock": "VERR",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "REGLAGES",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historique",
            "settings.labels": "Etiquettes",
            "settings.mapping": "Mappage",
            "settings.license": "Licence",
            "settings.language": "Langue",
            "settings.appearance": "Apparence",
            "appearance.title": "APPARENCE",
            "appearance.dark": "Mode sombre",
            "appearance.light": "Mode clair",
            "appearance.toggle": "Changer mode",
            "language.title": "LANGUE",
            "language.select": "Choisir la langue",
            "license.activate": "Activer",
            "license.deactivate": "Desactiver",
            "license.active": "Licence active",
            "license.inactive": "Sans licence",
            "license.monthly": "Mensuel",
            "license.lifetime": "A vie",
            "license.code": "Code d'activation",
            "license.enter": "Entrez le code...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Sauvegarder",
            "common.cancel": "Annuler",
            "common.close": "Fermer",
            "common.noSignal": "pas de signal",
            "common.clock": "HORLOGE",

            "settings.sources": "SOURCES",
            "settings.sources.subtitle": "Active ou désactive chaque protocole. Auto et Tous respectent ces cases.",
            "settings.sources.all": "Tous",
            "settings.sources.hint": "Dans l'en-tête, Auto utilise ces cases. Denon/Pioneer/… exclusifs ignorent le reste.",
            "settings.updates": "Mises à jour",
            "empty.searching": "Recherche de lecteurs sur le réseau…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "Contenu",
            "obs.tc": "Timecode (TC)",
            "obs.title": "Titre",
            "obs.artwork": "Pochette",
            "obs.meta": "Métadonnées (BPM, tonalité, artiste)",
            "obs.decks": "Decks",
            "appearance.dark.short": "Sombre",
            "appearance.light.short": "Clair",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER = LTC maison : un playhead, N sorties. Suit le deck master / On Air / en lecture.",
            "ltc.master.home": "MASTER MAISON",
            "ltc.network.emergency": "Urgence réseau",
            "ltc.outputs.master": "Sorties Master",
            "ltc.outputs.hint": "Choisissez une ou plusieurs. Le même TC est dupliqué sur chaque appareil.",
            "ltc.per.player": "PAR LECTEUR",
            "ltc.no.players": "Aucun lecteur visible. Chargez une piste pour assigner des sorties.",
            "ltc.outputs": "Sorties",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "Timecode MIDI pour DAW et lumières.",
            "mtc.port.hint": "Le port apparaît dans Audio MIDI Setup → Studio MIDI → STAGE CONNECT MTC.",
            "osc.title": "OSC vers Resolume",
            "osc.subtitle": "Tempo et playhead vers Resolume Arena / Avenue.",
            "web.title": "Serveur web",
            "web.subtitle": "Moniteur navigateur, JSON et WebSocket pour overlay (Resolume, OBS).",
            "web.on.this.mac": "Sur ce Mac",
            "web.on.lan": "Sur le réseau (autre machine)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "Ajoutez une Browser Source 1920×1080. Choisissez ce qui s'affiche.",
            "obs.enable.web": "Activez le serveur web pour obtenir l'URL. OBS : Browser Source, 1920×1080, 30 FPS.",
            "history.title": "Historique de lecture",
            "history.subtitle": "Pistes jouées dans cette session.",
            "history.empty": "L'historique se remplit automatiquement quand des pistes jouent.",
            "labels.title": "Étiquettes de decks",
            "labels.subtitle": "Noms courts personnalisés pour chaque lecteur.",
            "labels.open.monitor": "Ouvrir MONITOR",
            "labels.open.setlist": "Ouvrir SETLIST",
            "labels.empty": "Aucune étiquette. Cliquez A/1 sur une ligne pour renommer.",
            "mapping.title": "Mappage",
            "mapping.subtitle": "Raccourcis clavier et MIDI learn pour l'en-tête et le SMPTE.",
            "mapping.first.device": "Premier appareil",
            "mapping.hint.dual": "F1–F4 = 4 premières lignes visibles (SMPTE). Auto gère CDJ + couches Denon.",
            "appearance.subtitle": "Mode sombre ou clair.",
            "appearance.hint": "Le mode clair adapte fond et texte. Accents, LED et waveform restent identiques.",
            "updates.title": "Mises à jour",
            "updates.subtitle": "Vérifier et télécharger la dernière STAGE CONNECT.",
            "updates.notes": "Notes",
            "updates.action": "METTRE À JOUR",
            "license.title": "Licence",
            "license.subtitle": "État d'activation de STAGE CONNECT.",
            "license.remove": "RETIRER LA LICENCE",
            "monitor.title": "MONITOR",
            "monitor.options": "OPTIONS",
            "monitor.day": "JOUR",
            "monitor.night": "NUIT",
            "monitor.on.top": "DESSUS",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "OPACITÉ",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "ONDE",
            "monitor.opt.art": "POCHETTE",
            "monitor.opt.artist": "ARTISTE",
            "monitor.noMaster": "SANS MASTER",
            "monitor.mode.window": "FENÊTRE",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "TC seul",
            "monitor.layout.data": "Données",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "Cabine",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "Transparent",

        ],

        .it: [
            "header.master": "MASTER",
            "header.key": "TASTIERA",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "FISSO",
            "deck.notLoaded": "NESSUNA TRACCIA",
            "deck.noTitle": "SENZA TITOLO",
            "deck.play": "PLAY",
            "deck.pause": "PAUSA",
            "deck.stop": "STOP",
            "deck.lock": "BLOCCA",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "IMPOSTAZIONI",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Cronologia",
            "settings.labels": "Etichette",
            "settings.mapping": "Mappatura",
            "settings.license": "Licenza",
            "settings.language": "Lingua",
            "settings.appearance": "Aspetto",
            "appearance.title": "ASPETTO",
            "appearance.dark": "Modalita scura",
            "appearance.light": "Modalita chiara",
            "appearance.toggle": "Cambia modalita",
            "language.title": "LINGUA",
            "language.select": "Seleziona lingua",
            "license.activate": "Attiva",
            "license.deactivate": "Disattiva",
            "license.active": "Licenza attiva",
            "license.inactive": "Nessuna licenza",
            "license.monthly": "Mensile",
            "license.lifetime": "A vita",
            "license.code": "Codice di attivazione",
            "license.enter": "Inserisci il codice...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Salva",
            "common.cancel": "Annulla",
            "common.close": "Chiudi",
            "common.noSignal": "nessun segnale",
            "common.clock": "OROLOGIO",

            "settings.sources": "FONTI",
            "settings.sources.subtitle": "Attiva o disattiva ogni protocollo. Auto e Tutti rispettano queste spunte.",
            "settings.sources.all": "Tutti",
            "settings.sources.hint": "In intestazione, Auto usa queste spunte. Denon/Pioneer/… esclusivi ignorano il resto.",
            "settings.updates": "Aggiornamenti",
            "empty.searching": "Ricerca player in rete…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "Contenuto",
            "obs.tc": "Timecode (TC)",
            "obs.title": "Titolo",
            "obs.artwork": "Copertina",
            "obs.meta": "Metadati (BPM, tonalità, artista)",
            "obs.decks": "Deck",
            "appearance.dark.short": "Scuro",
            "appearance.light.short": "Chiaro",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER = LTC di casa: un playhead, N uscite. Segue master / On Air / in play.",
            "ltc.master.home": "MASTER DI CASA",
            "ltc.network.emergency": "Emergenza rete",
            "ltc.outputs.master": "Uscite Master",
            "ltc.outputs.hint": "Scegli una o più. Lo stesso TC si duplica su ogni device.",
            "ltc.per.player": "PER PLAYER",
            "ltc.no.players": "Nessun player visibile. Carica una traccia per assegnare uscite.",
            "ltc.outputs": "Uscite",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "Timecode MIDI per DAW e luci.",
            "mtc.port.hint": "La porta appare in Audio MIDI Setup → Studio MIDI → STAGE CONNECT MTC.",
            "osc.title": "OSC a Resolume",
            "osc.subtitle": "Tempo e playhead verso Resolume Arena / Avenue.",
            "web.title": "Server web",
            "web.subtitle": "Monitor browser, JSON e WebSocket per overlay (Resolume, OBS).",
            "web.on.this.mac": "Su questo Mac",
            "web.on.lan": "In rete (altro computer)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "Aggiungi Browser Source 1920×1080. Scegli cosa mostrare.",
            "obs.enable.web": "Attiva il server web per l'URL. OBS: Browser Source, 1920×1080, 30 FPS.",
            "history.title": "Cronologia riproduzione",
            "history.subtitle": "Tracce riprodotte in questa sessione.",
            "history.empty": "La cronologia si riempie automaticamente quando suonano tracce.",
            "labels.title": "Etichette deck",
            "labels.subtitle": "Nomi brevi personalizzati per ogni player.",
            "labels.open.monitor": "Apri MONITOR",
            "labels.open.setlist": "Apri SETLIST",
            "labels.empty": "Nessuna etichetta. Clic su A/1 di una riga per rinominare.",
            "mapping.title": "Mappatura",
            "mapping.subtitle": "Scorciatoie tastiera e MIDI learn per intestazione e SMPTE.",
            "mapping.first.device": "Primo dispositivo",
            "mapping.hint.dual": "F1–F4 = prime 4 righe visibili (SMPTE). Auto supporta CDJ + layer Denon.",
            "appearance.subtitle": "Modalità scura o chiara.",
            "appearance.hint": "La modalità chiara adatta sfondo e testo. Accenti, LED e waveform restano uguali.",
            "updates.title": "Aggiornamenti",
            "updates.subtitle": "Controlla e scarica l'ultima STAGE CONNECT.",
            "updates.notes": "Note",
            "updates.action": "AGGIORNA",
            "license.title": "Licenza",
            "license.subtitle": "Stato di attivazione di STAGE CONNECT.",
            "license.remove": "RIMUOVI LICENZA",
            "monitor.title": "MONITOR",
            "monitor.options": "OPZIONI",
            "monitor.day": "GIORNO",
            "monitor.night": "NOTTE",
            "monitor.on.top": "SOPRA",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "OPACITÀ",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "ONDA",
            "monitor.opt.art": "COPERTINA",
            "monitor.opt.artist": "ARTISTA",
            "monitor.noMaster": "SENZA MASTER",
            "monitor.mode.window": "FINESTRA",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "Solo TC",
            "monitor.layout.data": "Solo dati",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "Cabina",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "Trasparente",

        ],

        .de: [
            "header.master": "MASTER",
            "header.key": "TASTATUR",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "FIXIERT",
            "deck.notLoaded": "KEIN TRACK",
            "deck.noTitle": "KEIN TITEL",
            "deck.play": "PLAY",
            "deck.pause": "PAUSE",
            "deck.stop": "STOP",
            "deck.lock": "SPERREN",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "EINSTELLUNGEN",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Verlauf",
            "settings.labels": "Etiketten",
            "settings.mapping": "Zuweisung",
            "settings.license": "Lizenz",
            "settings.language": "Sprache",
            "settings.appearance": "Darstellung",
            "appearance.title": "DARSTELLUNG",
            "appearance.dark": "Dunkler Modus",
            "appearance.light": "Heller Modus",
            "appearance.toggle": "Modus wechseln",
            "language.title": "SPRACHE",
            "language.select": "Sprache wahlen",
            "license.activate": "Aktivieren",
            "license.deactivate": "Deaktivieren",
            "license.active": "Lizenz aktiv",
            "license.inactive": "Keine Lizenz",
            "license.monthly": "Monatlich",
            "license.lifetime": "Lebenslang",
            "license.code": "Aktivierungscode",
            "license.enter": "Code eingeben...",
            "common.on": "EIN",
            "common.off": "AUS",
            "common.save": "Speichern",
            "common.cancel": "Abbrechen",
            "common.close": "Schliessen",
            "common.noSignal": "kein Signal",
            "common.clock": "UHR",

            "settings.sources": "QUELLEN",
            "settings.sources.subtitle": "Protokoll einzeln aktivieren. Auto und Alle respektieren diese Häkchen.",
            "settings.sources.all": "Alle",
            "settings.sources.hint": "In der Kopfzeile nutzt Auto diese Häkchen. Exklusiv Denon/Pioneer/… ignorieren den Rest.",
            "settings.updates": "Updates",
            "empty.searching": "Suche Player im Netzwerk…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "Inhalt",
            "obs.tc": "Timecode (TC)",
            "obs.title": "Titel",
            "obs.artwork": "Cover",
            "obs.meta": "Metadaten (BPM, Tonart, Artist)",
            "obs.decks": "Decks",
            "appearance.dark.short": "Dunkel",
            "appearance.light.short": "Hell",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER = Haus-LTC: ein Playhead, N Ausgänge. Folgt Master / On Air / spielendem Deck.",
            "ltc.master.home": "HAUS-MASTER",
            "ltc.network.emergency": "Netz-Notfall",
            "ltc.outputs.master": "Master-Ausgänge",
            "ltc.outputs.hint": "Eine oder mehrere wählen. Derselbe TC wird auf jedes Gerät kopiert.",
            "ltc.per.player": "PRO PLAYER",
            "ltc.no.players": "Keine sichtbaren Player. Track laden, um Ausgänge zuzuweisen.",
            "ltc.outputs": "Ausgänge",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "MIDI-Timecode für DAW und Licht.",
            "mtc.port.hint": "Der Port erscheint in Audio MIDI Setup → MIDI-Studio → STAGE CONNECT MTC.",
            "osc.title": "OSC zu Resolume",
            "osc.subtitle": "Tempo und Playhead an Resolume Arena / Avenue.",
            "web.title": "Webserver",
            "web.subtitle": "Browser-Monitor, JSON und WebSocket für Overlay (Resolume, OBS).",
            "web.on.this.mac": "Auf diesem Mac",
            "web.on.lan": "Im Netzwerk (anderer Rechner)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "Browser Source 1920×1080 hinzufügen. Inhalt wählen.",
            "obs.enable.web": "Webserver aktivieren für die URL. OBS: Browser Source, 1920×1080, 30 FPS.",
            "history.title": "Wiedergabehistorie",
            "history.subtitle": "Tracks dieser Session.",
            "history.empty": "Die Historie füllt sich automatisch, wenn Tracks spielen.",
            "labels.title": "Deck-Labels",
            "labels.subtitle": "Kurznamen für jeden Player.",
            "labels.open.monitor": "MONITOR öffnen",
            "labels.open.setlist": "SETLIST öffnen",
            "labels.empty": "Keine Labels. Klick auf A/1 einer Zeile zum Umbenennen.",
            "mapping.title": "Mapping",
            "mapping.subtitle": "Tastaturkürzel und MIDI-Learn für Kopfzeile und SMPTE.",
            "mapping.first.device": "Erstes Gerät",
            "mapping.hint.dual": "F1–F4 = erste 4 sichtbare Zeilen (SMPTE). Auto unterstützt CDJ + Denon-Layer.",
            "appearance.subtitle": "Dunkel- oder Hellmodus.",
            "appearance.hint": "Hellmodus passt Hintergrund und Text an. Akzente, LED und Waveform bleiben.",
            "updates.title": "Updates",
            "updates.subtitle": "Neueste STAGE CONNECT prüfen und laden.",
            "updates.notes": "Notizen",
            "updates.action": "AKTUALISIEREN",
            "license.title": "Lizenz",
            "license.subtitle": "Aktivierungsstatus von STAGE CONNECT.",
            "license.remove": "LIZENZ ENTFERNEN",
            "monitor.title": "MONITOR",
            "monitor.options": "OPTIONEN",
            "monitor.day": "TAG",
            "monitor.night": "NACHT",
            "monitor.on.top": "OBEN",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "OPAZITÄT",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "WELLE",
            "monitor.opt.art": "COVER",
            "monitor.opt.artist": "ARTIST",
            "monitor.noMaster": "KEIN MASTER",
            "monitor.mode.window": "FENSTER",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "Nur TC",
            "monitor.layout.data": "Nur Daten",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "Booth",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "Transparent",

        ],

        .zh: [
            "header.master": "主控",
            "header.key": "键盘",
            "header.midi": "MIDI",
            "header.monitor": "监视器",
            "header.setlist": "歌单",
            "header.config": "设置",
            "header.log": "日志",
            "header.master.auto": "自动",
            "header.master.pin": "锁定",
            "deck.notLoaded": "无曲目",
            "deck.noTitle": "无标题",
            "deck.play": "播放",
            "deck.pause": "暂停",
            "deck.stop": "停止",
            "deck.lock": "锁",
            "deck.master": "主控",
            "deck.smpte": "SMPTE",
            "settings.title": "设置",
            "settings.subtitle": "配置",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "网络",
            "settings.obs": "OBS",
            "settings.history": "历史",
            "settings.labels": "标签",
            "settings.mapping": "映射",
            "settings.license": "许可证",
            "settings.language": "语言",
            "settings.appearance": "外观",
            "appearance.title": "外观",
            "appearance.dark": "深色模式",
            "appearance.light": "浅色模式",
            "appearance.toggle": "切换模式",
            "language.title": "语言",
            "language.select": "选择语言",
            "license.activate": "激活",
            "license.deactivate": "停用",
            "license.active": "许可证有效",
            "license.inactive": "无许可证",
            "license.monthly": "每月",
            "license.lifetime": "终身",
            "license.code": "激活码",
            "license.enter": "输入激活码...",
            "common.on": "开",
            "common.off": "关",
            "common.save": "保存",
            "common.cancel": "取消",
            "common.close": "关闭",
            "common.noSignal": "无信号",
            "common.clock": "时钟",

            "settings.sources": "音源",
            "settings.sources.subtitle": "分别启用各协议。自动与全部尊重这些勾选。",
            "settings.sources.all": "全部",
            "settings.sources.hint": "标题栏自动模式使用这些勾选。独占 Denon/Pioneer/… 忽略其余。",
            "settings.updates": "更新",
            "empty.searching": "正在搜索网络中的播放器…",
            "header.zoom": "缩放",
            "view.cdj": "CDJ",
            "view.overview": "总览",
            "view.master": "主控",
            "obs.content": "内容",
            "obs.tc": "时间码 (TC)",
            "obs.title": "标题",
            "obs.artwork": "封面",
            "obs.meta": "元数据（BPM、调性、艺人）",
            "obs.decks": "卡座",
            "appearance.dark.short": "暗色",
            "appearance.light.short": "亮色",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER 为本机 LTC：一个播放头，多路输出。跟随主控/On Air/正在播放。",
            "ltc.master.home": "本机 MASTER",
            "ltc.network.emergency": "网络应急",
            "ltc.outputs.master": "Master 输出",
            "ltc.outputs.hint": "可多选。同一 TC 复制到每台设备。",
            "ltc.per.player": "按播放器",
            "ltc.no.players": "没有可见播放器。加载曲目以分配输出。",
            "ltc.outputs": "输出",
            "ltc.tc.fps": "TC / 帧率",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "用于 DAW 与灯光的 MIDI 时间码。",
            "mtc.port.hint": "端口在 Audio MIDI Setup → MIDI Studio → STAGE CONNECT MTC。",
            "osc.title": "OSC 到 Resolume",
            "osc.subtitle": "向 Resolume Arena / Avenue 发送速度与播放头。",
            "web.title": "网页服务器",
            "web.subtitle": "浏览器监视器、JSON 与 WebSocket 叠加层。",
            "web.on.this.mac": "本机",
            "web.on.lan": "局域网（其他电脑）",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "添加 1920×1080 Browser Source。选择显示内容。",
            "obs.enable.web": "启用网页服务器以获取 URL。OBS：Browser Source，1920×1080，30 FPS。",
            "history.title": "播放历史",
            "history.subtitle": "本场次已播放曲目。",
            "history.empty": "有曲目播放时历史会自动填充。",
            "labels.title": "卡座标签",
            "labels.subtitle": "每个播放器的自定义短名。",
            "labels.open.monitor": "打开 MONITOR",
            "labels.open.setlist": "打开 SETLIST",
            "labels.empty": "暂无自定义标签。点击行上的 A/1 重命名。",
            "mapping.title": "映射",
            "mapping.subtitle": "标题栏与 SMPTE 的快捷键与 MIDI learn。",
            "mapping.first.device": "第一台设备",
            "mapping.hint.dual": "F1–F4 为前 4 行可见（SMPTE）。自动支持 CDJ + Denon 层。",
            "appearance.subtitle": "暗色或亮色界面。",
            "appearance.hint": "亮色模式调整背景与文字。强调色、LED 与波形不变。",
            "updates.title": "更新",
            "updates.subtitle": "检查并下载最新 STAGE CONNECT。",
            "updates.notes": "说明",
            "updates.action": "更新",
            "license.title": "许可证",
            "license.subtitle": "STAGE CONNECT 激活状态。",
            "license.remove": "移除许可证",
            "monitor.title": "MONITOR",
            "monitor.options": "选项",
            "monitor.day": "日",
            "monitor.night": "夜",
            "monitor.on.top": "置顶",
            "monitor.auto": "自动",
            "monitor.pin": "固定",
            "monitor.opacity": "不透明度",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "波形",
            "monitor.opt.art": "封面",
            "monitor.opt.artist": "艺人",
            "monitor.noMaster": "无主控",
            "monitor.mode.window": "窗口",
            "monitor.mode.overlay": "叠加",
            "monitor.mode.mini": "迷你",
            "monitor.layout.tc": "仅 TC",
            "monitor.layout.data": "仅数据",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "总览",
            "monitor.layout.tracklist": "歌单",
            "monitor.size.cabin": "亭",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "迷你",
            "obs.transparent": "透明",

        ],

        .ja: [
            "header.master": "マスター",
            "header.key": "キーボード",
            "header.midi": "MIDI",
            "header.monitor": "モニター",
            "header.setlist": "セットリスト",
            "header.config": "設定",
            "header.log": "ログ",
            "header.master.auto": "自動",
            "header.master.pin": "固定",
            "deck.notLoaded": "トラックなし",
            "deck.noTitle": "タイトルなし",
            "deck.play": "再生",
            "deck.pause": "一時停止",
            "deck.stop": "停止",
            "deck.lock": "ロック",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "設定",
            "settings.subtitle": "コンフィグ",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "履歴",
            "settings.labels": "ラベル",
            "settings.mapping": "マッピング",
            "settings.license": "ライセンス",
            "settings.language": "言語",
            "settings.appearance": "外観",
            "appearance.title": "外観",
            "appearance.dark": "ダークモード",
            "appearance.light": "ライトモード",
            "appearance.toggle": "モード切替",
            "language.title": "言語",
            "language.select": "言語を選択",
            "license.activate": "有効化",
            "license.deactivate": "無効化",
            "license.active": "ライセンス有効",
            "license.inactive": "ライセンスなし",
            "license.monthly": "月額",
            "license.lifetime": "永久",
            "license.code": "アクティベーションコード",
            "license.enter": "コードを入力...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "保存",
            "common.cancel": "キャンセル",
            "common.close": "閉じる",
            "common.noSignal": "信号なし",
            "common.clock": "クロック",

            "settings.sources": "ソース",
            "settings.sources.subtitle": "各プロトコルを個別に有効化。Auto とすべて はこれらのチェックに従います。",
            "settings.sources.all": "すべて",
            "settings.sources.hint": "ヘッダーの Auto はこれらのチェックを使います。単独の Denon/Pioneer/… は他を無視します。",
            "settings.updates": "アップデート",
            "empty.searching": "ネットワーク上のプレーヤーを検索中…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "コンテンツ",
            "obs.tc": "タイムコード (TC)",
            "obs.title": "タイトル",
            "obs.artwork": "ジャケット",
            "obs.meta": "メタデータ（BPM・キー・アーティスト）",
            "obs.decks": "デッキ",
            "appearance.dark.short": "ダーク",
            "appearance.light.short": "ライト",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER はハウス LTC：1 プレイヘッド、N 出力。マスター / On Air / 再生中に追従。",
            "ltc.master.home": "ハウス MASTER",
            "ltc.network.emergency": "ネットワーク緊急",
            "ltc.outputs.master": "Master 出力",
            "ltc.outputs.hint": "1 つ以上選択。同じ TC を各デバイスに複製。",
            "ltc.per.player": "プレーヤー別",
            "ltc.no.players": "表示中のプレーヤーなし。トラックを読み込んで出力を割り当て。",
            "ltc.outputs": "出力",
            "ltc.tc.fps": "TC / フレームレート",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "DAW と照明用 MIDI タイムコード。",
            "mtc.port.hint": "ポートは Audio MIDI Setup → MIDI Studio → STAGE CONNECT MTC。",
            "osc.title": "Resolume へ OSC",
            "osc.subtitle": "Resolume Arena / Avenue へテンポとプレイヘッド。",
            "web.title": "Web サーバー",
            "web.subtitle": "ブラウザモニター、JSON、WebSocket オーバーレイ。",
            "web.on.this.mac": "この Mac",
            "web.on.lan": "ネットワーク（他のマシン）",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "1920×1080 Browser Source を追加。表示内容を選択。",
            "obs.enable.web": "URL 用に Web サーバーを有効化。OBS：Browser Source、1920×1080、30 FPS。",
            "history.title": "再生履歴",
            "history.subtitle": "このセッションで再生したトラック。",
            "history.empty": "トラック再生時に履歴が自動で埋まります。",
            "labels.title": "デッキラベル",
            "labels.subtitle": "各プレーヤーの短い名前。",
            "labels.open.monitor": "MONITOR を開く",
            "labels.open.setlist": "SETLIST を開く",
            "labels.empty": "カスタムラベルなし。行の A/1 をクリックして変更。",
            "mapping.title": "マッピング",
            "mapping.subtitle": "ヘッダーと SMPTE のキーボード／MIDI learn。",
            "mapping.first.device": "最初のデバイス",
            "mapping.hint.dual": "F1–F4 は最初の 4 行（SMPTE）。Auto は CDJ + Denon レイヤー対応。",
            "appearance.subtitle": "ダークまたはライト。",
            "appearance.hint": "ライトは背景と文字を調整。アクセント・LED・波形は同じ。",
            "updates.title": "アップデート",
            "updates.subtitle": "最新の STAGE CONNECT を確認してダウンロード。",
            "updates.notes": "ノート",
            "updates.action": "更新",
            "license.title": "ライセンス",
            "license.subtitle": "STAGE CONNECT の有効化状態。",
            "license.remove": "ライセンスを削除",
            "monitor.title": "MONITOR",
            "monitor.options": "オプション",
            "monitor.day": "昼",
            "monitor.night": "夜",
            "monitor.on.top": "最前面",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "不透明度",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "波形",
            "monitor.opt.art": "ジャケット",
            "monitor.opt.artist": "アーティスト",
            "monitor.noMaster": "マスターなし",
            "monitor.mode.window": "ウィンドウ",
            "monitor.mode.overlay": "オーバーレイ",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "TCのみ",
            "monitor.layout.data": "データのみ",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "ブース",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "透明",

        ],

        .th: [
            "header.master": "มาสเตอร์",
            "header.key": "คีย์บอร์ด",
            "header.midi": "MIDI",
            "header.monitor": "มอนิเตอร์",
            "header.setlist": "เซตลิสต์",
            "header.config": "ตั้งค่า",
            "header.log": "ล็อก",
            "header.master.auto": "อัตโนมัติ",
            "header.master.pin": "ตรึง",
            "deck.notLoaded": "ไม่มีแทร็ก",
            "deck.noTitle": "ไม่มีชื่อ",
            "deck.play": "เล่น",
            "deck.pause": "หยุดชั่วคราว",
            "deck.stop": "หยุด",
            "deck.lock": "ล็อก",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "ตั้งค่า",
            "settings.subtitle": "การกำหนดค่า",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "เว็บ",
            "settings.obs": "OBS",
            "settings.history": "ประวัติ",
            "settings.labels": "ป้ายกำกับ",
            "settings.mapping": "การแมป",
            "settings.license": "ใบอนุญาต",
            "settings.language": "ภาษา",
            "settings.appearance": "รูปลักษณ์",
            "appearance.title": "รูปลักษณ์",
            "appearance.dark": "โหมดมืด",
            "appearance.light": "โหมดสว่าง",
            "appearance.toggle": "สลับโหมด",
            "language.title": "ภาษา",
            "language.select": "เลือกภาษา",
            "license.activate": "เปิดใช้งาน",
            "license.deactivate": "ปิดใช้งาน",
            "license.active": "ใบอนุญาตใช้งานได้",
            "license.inactive": "ไม่มีใบอนุญาต",
            "license.monthly": "รายเดือน",
            "license.lifetime": "ตลอดชีพ",
            "license.code": "รหัสเปิดใช้งาน",
            "license.enter": "ใส่รหัส...",
            "common.on": "เปิด",
            "common.off": "ปิด",
            "common.save": "บันทึก",
            "common.cancel": "ยกเลิก",
            "common.close": "ปิด",
            "common.noSignal": "ไม่มีสัญญาณ",
            "common.clock": "นาฬิกา",

            "settings.sources": "แหล่งสัญญาณ",
            "settings.sources.subtitle": "เปิด/ปิดแต่ละโปรโตคอล Auto และทั้งหมดเคารพช่องติ๊กเหล่านี้",
            "settings.sources.all": "ทั้งหมด",
            "settings.sources.hint": "ในส่วนหัว Auto ใช้ช่องติ๊กเหล่านี้ โหมดเดี่ยว Denon/Pioneer/… ไม่สนใจที่เหลือ",
            "settings.updates": "อัปเดต",
            "empty.searching": "กำลังค้นหาเครื่องเล่นในเครือข่าย…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "เนื้อหา",
            "obs.tc": "ไทม์โค้ด (TC)",
            "obs.title": "ชื่อเพลง",
            "obs.artwork": "ปกอัลบั้ม",
            "obs.meta": "เมทาดาทา (BPM, คีย์, ศิลปิน)",
            "obs.decks": "เด็ค",
            "appearance.dark.short": "มืด",
            "appearance.light.short": "สว่าง",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER คือ LTC บ้าน: playhead เดียว N เอาต์พุต ตาม master / On Air / กำลังเล่น",
            "ltc.master.home": "MASTER บ้าน",
            "ltc.network.emergency": "ฉุกเฉินเครือข่าย",
            "ltc.outputs.master": "เอาต์พุต Master",
            "ltc.outputs.hint": "เลือกอย่างน้อยหนึ่งรายการ TC เดียวกันคัดลอกไปทุกเครื่อง",
            "ltc.per.player": "ต่อเครื่องเล่น",
            "ltc.no.players": "ไม่เห็นเครื่องเล่น โหลดแทร็กเพื่อกำหนดเอาต์พุต",
            "ltc.outputs": "เอาต์พุต",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "ไทม์โค้ด MIDI สำหรับ DAW และไฟ",
            "mtc.port.hint": "พอร์ตอยู่ใน Audio MIDI Setup → MIDI Studio → STAGE CONNECT MTC",
            "osc.title": "OSC ไป Resolume",
            "osc.subtitle": "เทมโปและ playhead ไป Resolume Arena / Avenue",
            "web.title": "เว็บเซิร์ฟเวอร์",
            "web.subtitle": "มอนิเตอร์เบราว์เซอร์ JSON และ WebSocket สำหรับโอเวอร์เลย์",
            "web.on.this.mac": "บน Mac นี้",
            "web.on.lan": "บนเครือข่าย (เครื่องอื่น)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "เพิ่ม Browser Source 1920×1080 เลือกสิ่งที่แสดง",
            "obs.enable.web": "เปิดเว็บเซิร์ฟเวอร์เพื่อรับ URL OBS: Browser Source 1920×1080 30 FPS",
            "history.title": "ประวัติการเล่น",
            "history.subtitle": "แทร็กที่เล่นในเซสชันนี้",
            "history.empty": "ประวัติเติมอัตโนมัติเมื่อมีแทร็กเล่น",
            "labels.title": "ป้ายเด็ค",
            "labels.subtitle": "ชื่อสั้นกำหนดเองสำหรับแต่ละเครื่องเล่น",
            "labels.open.monitor": "เปิด MONITOR",
            "labels.open.setlist": "เปิด SETLIST",
            "labels.empty": "ยังไม่มีป้าย คลิก A/1 บนแถวเพื่อเปลี่ยนชื่อ",
            "mapping.title": "การแมป",
            "mapping.subtitle": "คีย์ลัดและ MIDI learn สำหรับส่วนหัวและ SMPTE",
            "mapping.first.device": "อุปกรณ์แรก",
            "mapping.hint.dual": "F1–F4 คือ 4 แถวแรกที่มองเห็น (SMPTE) Auto รองรับ CDJ + ชั้น Denon",
            "appearance.subtitle": "โหมดมืดหรือสว่าง",
            "appearance.hint": "โหมดสว่างปรับพื้นหลังและข้อความ สีเน้น LED และเวฟฟอร์มคงเดิม",
            "updates.title": "อัปเดต",
            "updates.subtitle": "ตรวจและดาวน์โหลด STAGE CONNECT ล่าสุด",
            "updates.notes": "บันทึก",
            "updates.action": "อัปเดต",
            "license.title": "ใบอนุญาต",
            "license.subtitle": "สถานะการเปิดใช้ STAGE CONNECT",
            "license.remove": "ลบใบอนุญาต",
            "monitor.title": "MONITOR",
            "monitor.options": "ตัวเลือก",
            "monitor.day": "วัน",
            "monitor.night": "คืน",
            "monitor.on.top": "บนสุด",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "ความทึบ",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "คลื่น",
            "monitor.opt.art": "ปก",
            "monitor.opt.artist": "ศิลปิน",
            "monitor.noMaster": "ไม่มี MASTER",
            "monitor.mode.window": "หน้าต่าง",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "เฉพาะ TC",
            "monitor.layout.data": "เฉพาะข้อมูล",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "บูธ",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "โปร่งใส",

        ],

        .ca: [
            "header.master": "MASTER",
            "header.key": "TECLAT",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "ANCORAT",
            "deck.notLoaded": "SENSE PISTA",
            "deck.noTitle": "SENSE TITOL",
            "deck.play": "PLAY",
            "deck.pause": "PAUSA",
            "deck.stop": "STOP",
            "deck.lock": "BLOQ",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "AJUSTOS",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historial",
            "settings.labels": "Etiquetes",
            "settings.mapping": "Mapatge",
            "settings.license": "Llicencia",
            "settings.language": "Idioma",
            "settings.appearance": "Aparenca",
            "appearance.title": "APARENCA",
            "appearance.dark": "Mode fosc",
            "appearance.light": "Mode clar",
            "appearance.toggle": "Canviar mode",
            "language.title": "IDIOMA",
            "language.select": "Seleccionar idioma",
            "license.activate": "Activar",
            "license.deactivate": "Desactivar",
            "license.active": "Llicencia activa",
            "license.inactive": "Sense llicencia",
            "license.monthly": "Mensual",
            "license.lifetime": "Vitalici",
            "license.code": "Codi d'activacio",
            "license.enter": "Introdueix el codi...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Desar",
            "common.cancel": "Cancel·lar",
            "common.close": "Tancar",
            "common.noSignal": "sense senyal",
            "common.clock": "RELLOTGE",

            "settings.sources": "FONTS",
            "settings.sources.subtitle": "Activa o desactiva cada protocol. Auto i Tots respecten aquestes marques.",
            "settings.sources.all": "Tots",
            "settings.sources.hint": "A la capçalera, Auto usa aquestes marques. Denon/Pioneer/… exclusius ignoren la resta.",
            "settings.updates": "Actualitzacions",
            "empty.searching": "Cercant reproductors a la xarxa…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "Contingut",
            "obs.tc": "Timecode (TC)",
            "obs.title": "Títol",
            "obs.artwork": "Portada",
            "obs.meta": "Metadades (BPM, tonalitat, artista)",
            "obs.decks": "Decks",
            "appearance.dark.short": "Fosc",
            "appearance.light.short": "Clar",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER és l'LTC de casa: un playhead, N sortides. Segueix master / On Air / en reproducció.",
            "ltc.master.home": "MASTER DE CASA",
            "ltc.network.emergency": "Emergència de xarxa",
            "ltc.outputs.master": "Sortides Master",
            "ltc.outputs.hint": "Tria'n una o més. El mateix TC es duplica a cada dispositiu.",
            "ltc.per.player": "PER REPRODUCTOR",
            "ltc.no.players": "No hi ha reproductors visibles. Carrega una pista per assignar sortides.",
            "ltc.outputs": "Sortides",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "Timecode MIDI per a DAW i llums.",
            "mtc.port.hint": "El port apareix a Audio MIDI Setup → Studio MIDI → STAGE CONNECT MTC.",
            "osc.title": "OSC a Resolume",
            "osc.subtitle": "Tempo i playhead cap a Resolume Arena / Avenue.",
            "web.title": "Servidor web",
            "web.subtitle": "Monitor al navegador, JSON i WebSocket per a overlay.",
            "web.on.this.mac": "En aquest Mac",
            "web.on.lan": "A la xarxa (un altre equip)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "Afegeix un Browser Source 1920×1080. Tria què es mostra.",
            "obs.enable.web": "Activa el servidor web per obtenir l'URL. OBS: Browser Source, 1920×1080, 30 FPS.",
            "history.title": "Historial de reproducció",
            "history.subtitle": "Pistes reproduïdes en aquesta sessió.",
            "history.empty": "L'historial s'omple automàticament quan sonen pistes.",
            "labels.title": "Etiquetes de decks",
            "labels.subtitle": "Noms curts personalitzats per a cada reproductor.",
            "labels.open.monitor": "Obrir MONITOR",
            "labels.open.setlist": "Obrir SETLIST",
            "labels.empty": "Cap etiqueta. Clic a A/1 d'una fila per canviar-la.",
            "mapping.title": "Mapatge",
            "mapping.subtitle": "Dreceres de teclat i MIDI learn per a capçalera i SMPTE.",
            "mapping.first.device": "Primer dispositiu",
            "mapping.hint.dual": "F1–F4 són les 4 primeres files visibles (SMPTE). Auto admet CDJ + capes Denon.",
            "appearance.subtitle": "Mode fosc o clar.",
            "appearance.hint": "El mode clar adapta fons i text. Els accents, LED i waveform no canvien.",
            "updates.title": "Actualitzacions",
            "updates.subtitle": "Comprova i descarrega l'última STAGE CONNECT.",
            "updates.notes": "Notes",
            "updates.action": "ACTUALITZAR",
            "license.title": "Llicència",
            "license.subtitle": "Estat d'activació de STAGE CONNECT.",
            "license.remove": "TREURE LLICÈNCIA",
            "monitor.title": "MONITOR",
            "monitor.options": "OPCIONS",
            "monitor.day": "DIA",
            "monitor.night": "NIT",
            "monitor.on.top": "DAMUNT",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "OPACITAT",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "ONA",
            "monitor.opt.art": "PORTADA",
            "monitor.opt.artist": "ARTISTA",
            "monitor.noMaster": "SENSE MASTER",
            "monitor.mode.window": "FINESTRA",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "Només TC",
            "monitor.layout.data": "Només dades",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "Cabina",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "Transparent",

        ],

        .gl: [
            "header.master": "MASTER",
            "header.key": "TECLADO",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "ANCRADO",
            "deck.notLoaded": "SEN PISTA",
            "deck.noTitle": "SEN TITULO",
            "deck.play": "PLAY",
            "deck.pause": "PAUSA",
            "deck.stop": "STOP",
            "deck.lock": "BLOQ",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "AXUSTES",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historial",
            "settings.labels": "Etiquetas",
            "settings.mapping": "Mapeado",
            "settings.license": "Licenza",
            "settings.language": "Idioma",
            "settings.appearance": "Aparencia",
            "appearance.title": "APARENCIA",
            "appearance.dark": "Modo escuro",
            "appearance.light": "Modo claro",
            "appearance.toggle": "Cambiar modo",
            "language.title": "IDIOMA",
            "language.select": "Seleccionar idioma",
            "license.activate": "Activar",
            "license.deactivate": "Desactivar",
            "license.active": "Licenza activa",
            "license.inactive": "Sen licenza",
            "license.monthly": "Mensual",
            "license.lifetime": "Vitalicio",
            "license.code": "Codigo de activacion",
            "license.enter": "Introduce o codigo...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Gardar",
            "common.cancel": "Cancelar",
            "common.close": "Pechar",
            "common.noSignal": "sen sinal",
            "common.clock": "RELOXO",

            "settings.sources": "FONTES",
            "settings.sources.subtitle": "Activa ou desactiva cada protocolo. Auto e Todos respectan estas marcas.",
            "settings.sources.all": "Todos",
            "settings.sources.hint": "Na cabeceira, Auto usa estas marcas. Denon/Pioneer/… exclusivos ignoran o resto.",
            "settings.updates": "Actualizacións",
            "empty.searching": "Buscando reprodutores na rede…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "Contido",
            "obs.tc": "Timecode (TC)",
            "obs.title": "Título",
            "obs.artwork": "Portada",
            "obs.meta": "Metadatos (BPM, tonaldade, artista)",
            "obs.decks": "Decks",
            "appearance.dark.short": "Escuro",
            "appearance.light.short": "Claro",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER é o LTC da casa: un playhead, N saídas. Segue master / On Air / en reprodución.",
            "ltc.master.home": "MASTER DA CASA",
            "ltc.network.emergency": "Emerxencia de rede",
            "ltc.outputs.master": "Saídas Master",
            "ltc.outputs.hint": "Escolle unha ou varias. O mesmo TC duplícase en cada dispositivo.",
            "ltc.per.player": "POR REPRODUTOR",
            "ltc.no.players": "Non hai reprodutores visibles. Carga unha pista para asignar saídas.",
            "ltc.outputs": "Saídas",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "Timecode MIDI para DAW e luces.",
            "mtc.port.hint": "O porto aparece en Audio MIDI Setup → Studio MIDI → STAGE CONNECT MTC.",
            "osc.title": "OSC a Resolume",
            "osc.subtitle": "Tempo e playhead cara a Resolume Arena / Avenue.",
            "web.title": "Servidor web",
            "web.subtitle": "Monitor no navegador, JSON e WebSocket para overlay.",
            "web.on.this.mac": "Neste Mac",
            "web.on.lan": "Na rede (outro equipo)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "Engade un Browser Source 1920×1080. Escolle o que se mostra.",
            "obs.enable.web": "Activa o servidor web para obter a URL. OBS: Browser Source, 1920×1080, 30 FPS.",
            "history.title": "Historial de reprodución",
            "history.subtitle": "Pistas reproducidas nesta sesión.",
            "history.empty": "O historial énchese automaticamente cando soan pistas.",
            "labels.title": "Etiquetas de decks",
            "labels.subtitle": "Nomes curtos personalizados para cada reprodutor.",
            "labels.open.monitor": "Abrir MONITOR",
            "labels.open.setlist": "Abrir SETLIST",
            "labels.empty": "Ningunha etiqueta. Clic en A/1 dunha fila para cambiala.",
            "mapping.title": "Mapeo",
            "mapping.subtitle": "Atallos de teclado e MIDI learn para cabeceira e SMPTE.",
            "mapping.first.device": "Primeiro dispositivo",
            "mapping.hint.dual": "F1–F4 son as primeiras 4 filas visibles (SMPTE). Auto admite CDJ + capas Denon.",
            "appearance.subtitle": "Modo escuro ou claro.",
            "appearance.hint": "O modo claro adapta fondo e texto. Os acentos, LED e waveform non cambian.",
            "updates.title": "Actualizacións",
            "updates.subtitle": "Comproba e descarga a última STAGE CONNECT.",
            "updates.notes": "Notas",
            "updates.action": "ACTUALIZAR",
            "license.title": "Licenza",
            "license.subtitle": "Estado de activación de STAGE CONNECT.",
            "license.remove": "QUITAR LICENZA",
            "monitor.title": "MONITOR",
            "monitor.options": "OPCIÓNS",
            "monitor.day": "DÍA",
            "monitor.night": "NOITE",
            "monitor.on.top": "ENriba",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "OPACIDADE",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "ONDA",
            "monitor.opt.art": "PORTADA",
            "monitor.opt.artist": "ARTISTA",
            "monitor.noMaster": "SEN MASTER",
            "monitor.mode.window": "XANELA",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "Só TC",
            "monitor.layout.data": "Só datos",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "Cabina",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "Transparente",

        ],

        .eu: [
            "header.master": "MASTER",
            "header.key": "TEKLATUA",
            "header.midi": "MIDI",
            "header.monitor": "MONITOREA",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "AINGURATUA",
            "deck.notLoaded": "PISTARIK EZ",
            "deck.noTitle": "IZENBURURIK EZ",
            "deck.play": "PLAY",
            "deck.pause": "GELDITU",
            "deck.stop": "STOP",
            "deck.lock": "BLOQ",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "EZARPENAK",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historia",
            "settings.labels": "Etiketak",
            "settings.mapping": "Mapaketa",
            "settings.license": "Lizentzia",
            "settings.language": "Hizkuntza",
            "settings.appearance": "Itxura",
            "appearance.title": "ITXURA",
            "appearance.dark": "Modu iluna",
            "appearance.light": "Modu argia",
            "appearance.toggle": "Modua aldatu",
            "language.title": "HIZKUNTZA",
            "language.select": "Hizkuntza hautatu",
            "license.activate": "Aktibatu",
            "license.deactivate": "Desaktibatu",
            "license.active": "Lizentzia aktibo",
            "license.inactive": "Lizentziarik ez",
            "license.monthly": "Hilabetekoa",
            "license.lifetime": "Betirako",
            "license.code": "Aktibazio kodea",
            "license.enter": "Kodea sartu...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Gorde",
            "common.cancel": "Utzi",
            "common.close": "Itxi",
            "common.noSignal": "seinalik ez",
            "common.clock": "ERLOJUA",

            "settings.sources": "ITURRIAK",
            "settings.sources.subtitle": "Aktibatu edo desaktibatu protokolo bakoitza. Auto eta Denak marka hauei jarraitzen diete.",
            "settings.sources.all": "Denak",
            "settings.sources.hint": "Goiburuan, Autok marka hauek erabiltzen ditu. Denon/Pioneer/… bakarrak gainerakoak ez ikusi.",
            "settings.updates": "Eguneraketak",
            "empty.searching": "Sarean erreproduzigailuak bilatzen…",
            "header.zoom": "ZOOM",
            "view.cdj": "CDJ",
            "view.overview": "Overview",
            "view.master": "Master",
            "obs.content": "Edukia",
            "obs.tc": "Timecode (TC)",
            "obs.title": "Izenburua",
            "obs.artwork": "Azala",
            "obs.meta": "Metadatuak (BPM, tonua, artista)",
            "obs.decks": "Deck-ak",
            "appearance.dark.short": "Iluna",
            "appearance.light.short": "Argia",
            "ltc.title": "SMPTE LTC",
            "ltc.subtitle": "MASTER etxeko LTC da: playhead bat, N irteera. Master / On Air / jotzen duenari jarraitzen dio.",
            "ltc.master.home": "ETXEKO MASTER",
            "ltc.network.emergency": "Sare larrialdia",
            "ltc.outputs.master": "Master irteerak",
            "ltc.outputs.hint": "Aukeratu bat edo gehiago. TC bera gailu bakoitzean bikoizten da.",
            "ltc.per.player": "ERREPRODUZIGAILEKA",
            "ltc.no.players": "Ez dago erreproduzigailurik. Kargatu pista bat irteerak esleitzeko.",
            "ltc.outputs": "Irteerak",
            "ltc.tc.fps": "TC / Frame rate",
            "mtc.title": "MIDI Timecode (MTC)",
            "mtc.subtitle": "MIDI timecode DAW eta argietarako.",
            "mtc.port.hint": "Ataka Audio MIDI Setup → MIDI Studio → STAGE CONNECT MTC-n agertzen da.",
            "osc.title": "OSC Resolumera",
            "osc.subtitle": "Tempoa eta playhead Resolume Arena / Avenue-ra.",
            "web.title": "Web zerbitzaria",
            "web.subtitle": "Arakatzaileko monitorea, JSON eta WebSocket overlay-rako.",
            "web.on.this.mac": "Mac honetan",
            "web.on.lan": "Sarean (beste ekipo bat)",
            "obs.title.section": "OBS Browser Source",
            "obs.subtitle": "Gehitu Browser Source 1920×1080. Aukeratu zer erakutsi.",
            "obs.enable.web": "Aktibatu web zerbitzaria URLa lortzeko. OBS: Browser Source, 1920×1080, 30 FPS.",
            "history.title": "Erreprodukzio-historia",
            "history.subtitle": "Saio honetan jotako pistak.",
            "history.empty": "Historia automatikoki betetzen da pistak jotzen direnean.",
            "labels.title": "Deck etiketak",
            "labels.subtitle": "Izen labur pertsonalizatuak erreproduzigailu bakoitzerako.",
            "labels.open.monitor": "Ireki MONITOR",
            "labels.open.setlist": "Ireki SETLIST",
            "labels.empty": "Ez dago etiketarik. Egin klik errenkadako A/1-ean izena aldatzeko.",
            "mapping.title": "Mapatzea",
            "mapping.subtitle": "Teklatuko lasterbideak eta MIDI learn goibururako eta SMPTE-rako.",
            "mapping.first.device": "Lehen gailua",
            "mapping.hint.dual": "F1–F4 lehen 4 errenkada ikusgaiak dira (SMPTE). Autok CDJ + Denon geruzak onartzen ditu.",
            "appearance.subtitle": "Modu iluna edo argia.",
            "appearance.hint": "Modu argiak atzeko planoa eta testua egokitzen ditu. Azentuak, LED eta waveform berdin.",
            "updates.title": "Eguneraketak",
            "updates.subtitle": "Egiaztatu eta deskargatu azken STAGE CONNECT.",
            "updates.notes": "Oharrak",
            "updates.action": "EGUNERATU",
            "license.title": "Lizentzia",
            "license.subtitle": "STAGE CONNECT aktibazio-egoera.",
            "license.remove": "KENDU LIZENTZIA",
            "monitor.title": "MONITOR",
            "monitor.options": "AUKERAK",
            "monitor.day": "EGUNA",
            "monitor.night": "GAUA",
            "monitor.on.top": "GAINEAN",
            "monitor.auto": "AUTO",
            "monitor.pin": "PIN",
            "monitor.opacity": "OPAKUTASUNA",
            "monitor.opt.bpm": "BPM",
            "monitor.opt.wave": "UHINA",
            "monitor.opt.art": "AZALA",
            "monitor.opt.artist": "ARTISTA",
            "monitor.noMaster": "MASTERIK EZ",
            "monitor.mode.window": "LEIHOA",
            "monitor.mode.overlay": "OVERLAY",
            "monitor.mode.mini": "MINI",
            "monitor.layout.tc": "TC bakarrik",
            "monitor.layout.data": "Datuak bakarrik",
            "monitor.layout.cdj": "CDJ",
            "monitor.layout.overview": "Overview",
            "monitor.layout.tracklist": "Tracklist",
            "monitor.size.cabin": "Kabina",
            "monitor.size.hd": "1080p",
            "monitor.size.mini": "Mini",
            "obs.transparent": "Gardena",

        ],
    ]
}
