// LocalizationStore.swift
// Selector de idioma en tiempo de ejecucion: 11 idiomas.

import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case es = "es"
    case en = "en"
    case fr = "fr"
    case it = "it"
    case de = "de"
    case zh = "zh"
    case ja = "ja"
    case th = "th"
    case ca = "ca"
    case gl = "gl"
    case eu = "eu"

    var id: String { rawValue }

    var displayName: String {
        switch self {
        case .es: return "Español"
        case .en: return "English"
        case .fr: return "Français"
        case .it: return "Italiano"
        case .de: return "Deutsch"
        case .zh: return "中文"
        case .ja: return "日本語"
        case .th: return "ภาษาไทย"
        case .ca: return "Català"
        case .gl: return "Galego"
        case .eu: return "Euskera"
        }
    }

    var flag: String {
        switch self {
        case .es: return "ES"
        case .en: return "EN"
        case .fr: return "FR"
        case .it: return "IT"
        case .de: return "DE"
        case .zh: return "ZH"
        case .ja: return "JA"
        case .th: return "TH"
        case .ca: return "CA"
        case .gl: return "GL"
        case .eu: return "EU"
        }
    }
}

final class LocalizationStore: ObservableObject {
    @Published var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: "sc.language") }
    }

    init() {
        let saved = UserDefaults.standard.string(forKey: "sc.language") ?? "es"
        self.language = AppLanguage(rawValue: saved) ?? .es
    }

    func t(_ key: String) -> String {
        strings[language]?[key] ?? strings[.es]?[key] ?? key
    }

    // MARK: - Diccionario de cadenas

    private let strings: [AppLanguage: [String: String]] = [

        .es: [
            // Header
            "header.master": "MASTER",
            "header.key": "TECLADO",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "ANCLADO",
            // Deck
            "deck.notLoaded": "SIN PISTA",
            "deck.noTitle": "SIN TITULO",
            "deck.play": "PLAY",
            "deck.pause": "PAUSA",
            "deck.stop": "STOP",
            "deck.lock": "LOCK",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            // Settings sections
            "settings.title": "CONFIG",
            "settings.subtitle": "AJUSTES",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historial",
            "settings.labels": "Etiquetas",
            "settings.mapping": "Mapeo",
            "settings.license": "Licencia",
            "settings.language": "Idioma",
            "settings.appearance": "Apariencia",
            // Appearance
            "appearance.title": "APARIENCIA",
            "appearance.dark": "Modo oscuro",
            "appearance.light": "Modo claro",
            "appearance.toggle": "Cambiar modo",
            // Language
            "language.title": "IDIOMA",
            "language.select": "Seleccionar idioma",
            // License
            "license.activate": "Activar",
            "license.deactivate": "Desactivar",
            "license.active": "Licencia activa",
            "license.inactive": "Sin licencia",
            "license.monthly": "Mensual",
            "license.lifetime": "Vitalicio",
            "license.code": "Codigo de activacion",
            "license.enter": "Introduce el codigo...",
            // Common
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Guardar",
            "common.cancel": "Cancelar",
            "common.close": "Cerrar",
            "common.noSignal": "sin señal",
            "common.clock": "RELOJ",
        ],

        .en: [
            "header.master": "MASTER",
            "header.key": "KEYBOARD",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "PINNED",
            "deck.notLoaded": "NO TRACK",
            "deck.noTitle": "NO TITLE",
            "deck.play": "PLAY",
            "deck.pause": "PAUSE",
            "deck.stop": "STOP",
            "deck.lock": "LOCK",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "SETTINGS",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "History",
            "settings.labels": "Labels",
            "settings.mapping": "Mapping",
            "settings.license": "License",
            "settings.language": "Language",
            "settings.appearance": "Appearance",
            "appearance.title": "APPEARANCE",
            "appearance.dark": "Dark mode",
            "appearance.light": "Light mode",
            "appearance.toggle": "Toggle mode",
            "language.title": "LANGUAGE",
            "language.select": "Select language",
            "license.activate": "Activate",
            "license.deactivate": "Deactivate",
            "license.active": "License active",
            "license.inactive": "No license",
            "license.monthly": "Monthly",
            "license.lifetime": "Lifetime",
            "license.code": "Activation code",
            "license.enter": "Enter code...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Save",
            "common.cancel": "Cancel",
            "common.close": "Close",
            "common.noSignal": "no signal",
            "common.clock": "CLOCK",
        ],

        .fr: [
            "header.master": "MASTER",
            "header.key": "CLAVIER",
            "header.midi": "MIDI",
            "header.monitor": "MONITEUR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "FIXE",
            "deck.notLoaded": "SANS PISTE",
            "deck.noTitle": "SANS TITRE",
            "deck.play": "PLAY",
            "deck.pause": "PAUSE",
            "deck.stop": "STOP",
            "deck.lock": "VERR",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "REGLAGES",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historique",
            "settings.labels": "Etiquettes",
            "settings.mapping": "Mappage",
            "settings.license": "Licence",
            "settings.language": "Langue",
            "settings.appearance": "Apparence",
            "appearance.title": "APPARENCE",
            "appearance.dark": "Mode sombre",
            "appearance.light": "Mode clair",
            "appearance.toggle": "Changer mode",
            "language.title": "LANGUE",
            "language.select": "Choisir la langue",
            "license.activate": "Activer",
            "license.deactivate": "Desactiver",
            "license.active": "Licence active",
            "license.inactive": "Sans licence",
            "license.monthly": "Mensuel",
            "license.lifetime": "A vie",
            "license.code": "Code d'activation",
            "license.enter": "Entrez le code...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Sauvegarder",
            "common.cancel": "Annuler",
            "common.close": "Fermer",
            "common.noSignal": "pas de signal",
            "common.clock": "HORLOGE",
        ],

        .it: [
            "header.master": "MASTER",
            "header.key": "TASTIERA",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "FISSO",
            "deck.notLoaded": "NESSUNA TRACCIA",
            "deck.noTitle": "SENZA TITOLO",
            "deck.play": "PLAY",
            "deck.pause": "PAUSA",
            "deck.stop": "STOP",
            "deck.lock": "BLOCCA",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "IMPOSTAZIONI",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Cronologia",
            "settings.labels": "Etichette",
            "settings.mapping": "Mappatura",
            "settings.license": "Licenza",
            "settings.language": "Lingua",
            "settings.appearance": "Aspetto",
            "appearance.title": "ASPETTO",
            "appearance.dark": "Modalita scura",
            "appearance.light": "Modalita chiara",
            "appearance.toggle": "Cambia modalita",
            "language.title": "LINGUA",
            "language.select": "Seleziona lingua",
            "license.activate": "Attiva",
            "license.deactivate": "Disattiva",
            "license.active": "Licenza attiva",
            "license.inactive": "Nessuna licenza",
            "license.monthly": "Mensile",
            "license.lifetime": "A vita",
            "license.code": "Codice di attivazione",
            "license.enter": "Inserisci il codice...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Salva",
            "common.cancel": "Annulla",
            "common.close": "Chiudi",
            "common.noSignal": "nessun segnale",
            "common.clock": "OROLOGIO",
        ],

        .de: [
            "header.master": "MASTER",
            "header.key": "TASTATUR",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "FIXIERT",
            "deck.notLoaded": "KEIN TRACK",
            "deck.noTitle": "KEIN TITEL",
            "deck.play": "PLAY",
            "deck.pause": "PAUSE",
            "deck.stop": "STOP",
            "deck.lock": "SPERREN",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "EINSTELLUNGEN",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Verlauf",
            "settings.labels": "Etiketten",
            "settings.mapping": "Zuweisung",
            "settings.license": "Lizenz",
            "settings.language": "Sprache",
            "settings.appearance": "Darstellung",
            "appearance.title": "DARSTELLUNG",
            "appearance.dark": "Dunkler Modus",
            "appearance.light": "Heller Modus",
            "appearance.toggle": "Modus wechseln",
            "language.title": "SPRACHE",
            "language.select": "Sprache wahlen",
            "license.activate": "Aktivieren",
            "license.deactivate": "Deaktivieren",
            "license.active": "Lizenz aktiv",
            "license.inactive": "Keine Lizenz",
            "license.monthly": "Monatlich",
            "license.lifetime": "Lebenslang",
            "license.code": "Aktivierungscode",
            "license.enter": "Code eingeben...",
            "common.on": "EIN",
            "common.off": "AUS",
            "common.save": "Speichern",
            "common.cancel": "Abbrechen",
            "common.close": "Schliessen",
            "common.noSignal": "kein Signal",
            "common.clock": "UHR",
        ],

        .zh: [
            "header.master": "主控",
            "header.key": "键盘",
            "header.midi": "MIDI",
            "header.monitor": "监视器",
            "header.setlist": "歌单",
            "header.config": "设置",
            "header.log": "日志",
            "header.master.auto": "自动",
            "header.master.pin": "锁定",
            "deck.notLoaded": "无曲目",
            "deck.noTitle": "无标题",
            "deck.play": "播放",
            "deck.pause": "暂停",
            "deck.stop": "停止",
            "deck.lock": "锁",
            "deck.master": "主控",
            "deck.smpte": "SMPTE",
            "settings.title": "设置",
            "settings.subtitle": "配置",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "网络",
            "settings.obs": "OBS",
            "settings.history": "历史",
            "settings.labels": "标签",
            "settings.mapping": "映射",
            "settings.license": "许可证",
            "settings.language": "语言",
            "settings.appearance": "外观",
            "appearance.title": "外观",
            "appearance.dark": "深色模式",
            "appearance.light": "浅色模式",
            "appearance.toggle": "切换模式",
            "language.title": "语言",
            "language.select": "选择语言",
            "license.activate": "激活",
            "license.deactivate": "停用",
            "license.active": "许可证有效",
            "license.inactive": "无许可证",
            "license.monthly": "每月",
            "license.lifetime": "终身",
            "license.code": "激活码",
            "license.enter": "输入激活码...",
            "common.on": "开",
            "common.off": "关",
            "common.save": "保存",
            "common.cancel": "取消",
            "common.close": "关闭",
            "common.noSignal": "无信号",
            "common.clock": "时钟",
        ],

        .ja: [
            "header.master": "マスター",
            "header.key": "キーボード",
            "header.midi": "MIDI",
            "header.monitor": "モニター",
            "header.setlist": "セットリスト",
            "header.config": "設定",
            "header.log": "ログ",
            "header.master.auto": "自動",
            "header.master.pin": "固定",
            "deck.notLoaded": "トラックなし",
            "deck.noTitle": "タイトルなし",
            "deck.play": "再生",
            "deck.pause": "一時停止",
            "deck.stop": "停止",
            "deck.lock": "ロック",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "設定",
            "settings.subtitle": "コンフィグ",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "履歴",
            "settings.labels": "ラベル",
            "settings.mapping": "マッピング",
            "settings.license": "ライセンス",
            "settings.language": "言語",
            "settings.appearance": "外観",
            "appearance.title": "外観",
            "appearance.dark": "ダークモード",
            "appearance.light": "ライトモード",
            "appearance.toggle": "モード切替",
            "language.title": "言語",
            "language.select": "言語を選択",
            "license.activate": "有効化",
            "license.deactivate": "無効化",
            "license.active": "ライセンス有効",
            "license.inactive": "ライセンスなし",
            "license.monthly": "月額",
            "license.lifetime": "永久",
            "license.code": "アクティベーションコード",
            "license.enter": "コードを入力...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "保存",
            "common.cancel": "キャンセル",
            "common.close": "閉じる",
            "common.noSignal": "信号なし",
            "common.clock": "クロック",
        ],

        .th: [
            "header.master": "มาสเตอร์",
            "header.key": "คีย์บอร์ด",
            "header.midi": "MIDI",
            "header.monitor": "มอนิเตอร์",
            "header.setlist": "เซตลิสต์",
            "header.config": "ตั้งค่า",
            "header.log": "ล็อก",
            "header.master.auto": "อัตโนมัติ",
            "header.master.pin": "ตรึง",
            "deck.notLoaded": "ไม่มีแทร็ก",
            "deck.noTitle": "ไม่มีชื่อ",
            "deck.play": "เล่น",
            "deck.pause": "หยุดชั่วคราว",
            "deck.stop": "หยุด",
            "deck.lock": "ล็อก",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "ตั้งค่า",
            "settings.subtitle": "การกำหนดค่า",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "เว็บ",
            "settings.obs": "OBS",
            "settings.history": "ประวัติ",
            "settings.labels": "ป้ายกำกับ",
            "settings.mapping": "การแมป",
            "settings.license": "ใบอนุญาต",
            "settings.language": "ภาษา",
            "settings.appearance": "รูปลักษณ์",
            "appearance.title": "รูปลักษณ์",
            "appearance.dark": "โหมดมืด",
            "appearance.light": "โหมดสว่าง",
            "appearance.toggle": "สลับโหมด",
            "language.title": "ภาษา",
            "language.select": "เลือกภาษา",
            "license.activate": "เปิดใช้งาน",
            "license.deactivate": "ปิดใช้งาน",
            "license.active": "ใบอนุญาตใช้งานได้",
            "license.inactive": "ไม่มีใบอนุญาต",
            "license.monthly": "รายเดือน",
            "license.lifetime": "ตลอดชีพ",
            "license.code": "รหัสเปิดใช้งาน",
            "license.enter": "ใส่รหัส...",
            "common.on": "เปิด",
            "common.off": "ปิด",
            "common.save": "บันทึก",
            "common.cancel": "ยกเลิก",
            "common.close": "ปิด",
            "common.noSignal": "ไม่มีสัญญาณ",
            "common.clock": "นาฬิกา",
        ],

        .ca: [
            "header.master": "MASTER",
            "header.key": "TECLAT",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "ANCORAT",
            "deck.notLoaded": "SENSE PISTA",
            "deck.noTitle": "SENSE TITOL",
            "deck.play": "PLAY",
            "deck.pause": "PAUSA",
            "deck.stop": "STOP",
            "deck.lock": "BLOQ",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "AJUSTOS",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historial",
            "settings.labels": "Etiquetes",
            "settings.mapping": "Mapatge",
            "settings.license": "Llicencia",
            "settings.language": "Idioma",
            "settings.appearance": "Aparenca",
            "appearance.title": "APARENCA",
            "appearance.dark": "Mode fosc",
            "appearance.light": "Mode clar",
            "appearance.toggle": "Canviar mode",
            "language.title": "IDIOMA",
            "language.select": "Seleccionar idioma",
            "license.activate": "Activar",
            "license.deactivate": "Desactivar",
            "license.active": "Llicencia activa",
            "license.inactive": "Sense llicencia",
            "license.monthly": "Mensual",
            "license.lifetime": "Vitalici",
            "license.code": "Codi d'activacio",
            "license.enter": "Introdueix el codi...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Desar",
            "common.cancel": "Cancel·lar",
            "common.close": "Tancar",
            "common.noSignal": "sense senyal",
            "common.clock": "RELLOTGE",
        ],

        .gl: [
            "header.master": "MASTER",
            "header.key": "TECLADO",
            "header.midi": "MIDI",
            "header.monitor": "MONITOR",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "ANCRADO",
            "deck.notLoaded": "SEN PISTA",
            "deck.noTitle": "SEN TITULO",
            "deck.play": "PLAY",
            "deck.pause": "PAUSA",
            "deck.stop": "STOP",
            "deck.lock": "BLOQ",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "AXUSTES",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historial",
            "settings.labels": "Etiquetas",
            "settings.mapping": "Mapeado",
            "settings.license": "Licenza",
            "settings.language": "Idioma",
            "settings.appearance": "Aparencia",
            "appearance.title": "APARENCIA",
            "appearance.dark": "Modo escuro",
            "appearance.light": "Modo claro",
            "appearance.toggle": "Cambiar modo",
            "language.title": "IDIOMA",
            "language.select": "Seleccionar idioma",
            "license.activate": "Activar",
            "license.deactivate": "Desactivar",
            "license.active": "Licenza activa",
            "license.inactive": "Sen licenza",
            "license.monthly": "Mensual",
            "license.lifetime": "Vitalicio",
            "license.code": "Codigo de activacion",
            "license.enter": "Introduce o codigo...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Gardar",
            "common.cancel": "Cancelar",
            "common.close": "Pechar",
            "common.noSignal": "sen sinal",
            "common.clock": "RELOXO",
        ],

        .eu: [
            "header.master": "MASTER",
            "header.key": "TEKLATUA",
            "header.midi": "MIDI",
            "header.monitor": "MONITOREA",
            "header.setlist": "SETLIST",
            "header.config": "CONFIG",
            "header.log": "LOG",
            "header.master.auto": "AUTO",
            "header.master.pin": "AINGURATUA",
            "deck.notLoaded": "PISTARIK EZ",
            "deck.noTitle": "IZENBURURIK EZ",
            "deck.play": "PLAY",
            "deck.pause": "GELDITU",
            "deck.stop": "STOP",
            "deck.lock": "BLOQ",
            "deck.master": "MST",
            "deck.smpte": "SMPTE",
            "settings.title": "CONFIG",
            "settings.subtitle": "EZARPENAK",
            "settings.ltc": "LTC",
            "settings.mtc": "MTC",
            "settings.osc": "OSC",
            "settings.web": "Web",
            "settings.obs": "OBS",
            "settings.history": "Historia",
            "settings.labels": "Etiketak",
            "settings.mapping": "Mapaketa",
            "settings.license": "Lizentzia",
            "settings.language": "Hizkuntza",
            "settings.appearance": "Itxura",
            "appearance.title": "ITXURA",
            "appearance.dark": "Modu iluna",
            "appearance.light": "Modu argia",
            "appearance.toggle": "Modua aldatu",
            "language.title": "HIZKUNTZA",
            "language.select": "Hizkuntza hautatu",
            "license.activate": "Aktibatu",
            "license.deactivate": "Desaktibatu",
            "license.active": "Lizentzia aktibo",
            "license.inactive": "Lizentziarik ez",
            "license.monthly": "Hilabetekoa",
            "license.lifetime": "Betirako",
            "license.code": "Aktibazio kodea",
            "license.enter": "Kodea sartu...",
            "common.on": "ON",
            "common.off": "OFF",
            "common.save": "Gorde",
            "common.cancel": "Utzi",
            "common.close": "Itxi",
            "common.noSignal": "seinalik ez",
            "common.clock": "ERLOJUA",
        ],
    ]
}
