name: Build & Test (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    name: swift build (macOS)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Swift version
        run: swift --version

      - name: Build (debug)
        run: swift build -v

      - name: Build (release)
        run: swift build -c release -v

      - name: Run tests
        run: swift test -v
        continue-on-error: true
